// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: studytimer/v1/timer.proto

package timerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StudyTimerService_StartTimer_FullMethodName         = "/fishertimer.studytimer.v1.StudyTimerService/StartTimer"
	StudyTimerService_GetTimer_FullMethodName           = "/fishertimer.studytimer.v1.StudyTimerService/GetTimer"
	StudyTimerService_GetRoomTimers_FullMethodName      = "/fishertimer.studytimer.v1.StudyTimerService/GetRoomTimers"
	StudyTimerService_PauseTimer_FullMethodName         = "/fishertimer.studytimer.v1.StudyTimerService/PauseTimer"
	StudyTimerService_ResumeTimer_FullMethodName        = "/fishertimer.studytimer.v1.StudyTimerService/ResumeTimer"
	StudyTimerService_StopTimer_FullMethodName          = "/fishertimer.studytimer.v1.StudyTimerService/StopTimer"
	StudyTimerService_ResetTimer_FullMethodName         = "/fishertimer.studytimer.v1.StudyTimerService/ResetTimer"
	StudyTimerService_CompleteCycle_FullMethodName      = "/fishertimer.studytimer.v1.StudyTimerService/CompleteCycle"
	StudyTimerService_SkipRest_FullMethodName           = "/fishertimer.studytimer.v1.StudyTimerService/SkipRest"
	StudyTimerService_UpdateTimerSetting_FullMethodName = "/fishertimer.studytimer.v1.StudyTimerService/UpdateTimerSetting"
	StudyTimerService_TimerStatistics_FullMethodName    = "/fishertimer.studytimer.v1.StudyTimerService/TimerStatistics"
)

// StudyTimerServiceClient is the client API for StudyTimerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StudyTimerService runs one independent timer per participant per room
// (UC-05). Every RPC that changes the timer returns its full state, so the
// caller never has to issue a follow-up GetTimer.
type StudyTimerServiceClient interface {
	// Starts a new work cycle, or restarts one from the top.
	StartTimer(ctx context.Context, in *StartTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	// Reads the timer's current state and remaining time.
	GetTimer(ctx context.Context, in *GetTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	// Reads all active participant timers for a room (session_id).
	GetRoomTimers(ctx context.Context, in *GetRoomTimersRequest, opts ...grpc.CallOption) (*GetRoomTimersResponse, error)
	// Freezes the remaining time of a running timer.
	PauseTimer(ctx context.Context, in *PauseTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	// Continues a paused timer from where it was frozen.
	ResumeTimer(ctx context.Context, in *ResumeTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	StopTimer(ctx context.Context, in *StopTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	// Discards the timer and returns it to its initial, stopped state.
	ResetTimer(ctx context.Context, in *ResetTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	CompleteCycle(ctx context.Context, in *CompleteCycleRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	SkipRest(ctx context.Context, in *SkipRestRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	UpdateTimerSetting(ctx context.Context, in *UpdateTimerSettingRequest, opts ...grpc.CallOption) (*TimerStateResponse, error)
	TimerStatistics(ctx context.Context, in *TimerStatisticsRequest, opts ...grpc.CallOption) (*TimerStatisticsResponse, error)
}

type studyTimerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudyTimerServiceClient(cc grpc.ClientConnInterface) StudyTimerServiceClient {
	return &studyTimerServiceClient{cc}
}

func (c *studyTimerServiceClient) StartTimer(ctx context.Context, in *StartTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_StartTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) GetTimer(ctx context.Context, in *GetTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_GetTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) GetRoomTimers(ctx context.Context, in *GetRoomTimersRequest, opts ...grpc.CallOption) (*GetRoomTimersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomTimersResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_GetRoomTimers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) PauseTimer(ctx context.Context, in *PauseTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_PauseTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) ResumeTimer(ctx context.Context, in *ResumeTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_ResumeTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) StopTimer(ctx context.Context, in *StopTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_StopTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) ResetTimer(ctx context.Context, in *ResetTimerRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_ResetTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) CompleteCycle(ctx context.Context, in *CompleteCycleRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_CompleteCycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) SkipRest(ctx context.Context, in *SkipRestRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_SkipRest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) UpdateTimerSetting(ctx context.Context, in *UpdateTimerSettingRequest, opts ...grpc.CallOption) (*TimerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStateResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_UpdateTimerSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyTimerServiceClient) TimerStatistics(ctx context.Context, in *TimerStatisticsRequest, opts ...grpc.CallOption) (*TimerStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerStatisticsResponse)
	err := c.cc.Invoke(ctx, StudyTimerService_TimerStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyTimerServiceServer is the server API for StudyTimerService service.
// All implementations must embed UnimplementedStudyTimerServiceServer
// for forward compatibility.
//
// StudyTimerService runs one independent timer per participant per room
// (UC-05). Every RPC that changes the timer returns its full state, so the
// caller never has to issue a follow-up GetTimer.
type StudyTimerServiceServer interface {
	// Starts a new work cycle, or restarts one from the top.
	StartTimer(context.Context, *StartTimerRequest) (*TimerStateResponse, error)
	// Reads the timer's current state and remaining time.
	GetTimer(context.Context, *GetTimerRequest) (*TimerStateResponse, error)
	// Reads all active participant timers for a room (session_id).
	GetRoomTimers(context.Context, *GetRoomTimersRequest) (*GetRoomTimersResponse, error)
	// Freezes the remaining time of a running timer.
	PauseTimer(context.Context, *PauseTimerRequest) (*TimerStateResponse, error)
	// Continues a paused timer from where it was frozen.
	ResumeTimer(context.Context, *ResumeTimerRequest) (*TimerStateResponse, error)
	StopTimer(context.Context, *StopTimerRequest) (*TimerStateResponse, error)
	// Discards the timer and returns it to its initial, stopped state.
	ResetTimer(context.Context, *ResetTimerRequest) (*TimerStateResponse, error)
	CompleteCycle(context.Context, *CompleteCycleRequest) (*TimerStateResponse, error)
	SkipRest(context.Context, *SkipRestRequest) (*TimerStateResponse, error)
	UpdateTimerSetting(context.Context, *UpdateTimerSettingRequest) (*TimerStateResponse, error)
	TimerStatistics(context.Context, *TimerStatisticsRequest) (*TimerStatisticsResponse, error)
	mustEmbedUnimplementedStudyTimerServiceServer()
}

// UnimplementedStudyTimerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudyTimerServiceServer struct{}

func (UnimplementedStudyTimerServiceServer) StartTimer(context.Context, *StartTimerRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTimer not implemented")
}
func (UnimplementedStudyTimerServiceServer) GetTimer(context.Context, *GetTimerRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimer not implemented")
}
func (UnimplementedStudyTimerServiceServer) GetRoomTimers(context.Context, *GetRoomTimersRequest) (*GetRoomTimersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoomTimers not implemented")
}
func (UnimplementedStudyTimerServiceServer) PauseTimer(context.Context, *PauseTimerRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseTimer not implemented")
}
func (UnimplementedStudyTimerServiceServer) ResumeTimer(context.Context, *ResumeTimerRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeTimer not implemented")
}
func (UnimplementedStudyTimerServiceServer) StopTimer(context.Context, *StopTimerRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTimer not implemented")
}
func (UnimplementedStudyTimerServiceServer) ResetTimer(context.Context, *ResetTimerRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetTimer not implemented")
}
func (UnimplementedStudyTimerServiceServer) CompleteCycle(context.Context, *CompleteCycleRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteCycle not implemented")
}
func (UnimplementedStudyTimerServiceServer) SkipRest(context.Context, *SkipRestRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SkipRest not implemented")
}
func (UnimplementedStudyTimerServiceServer) UpdateTimerSetting(context.Context, *UpdateTimerSettingRequest) (*TimerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTimerSetting not implemented")
}
func (UnimplementedStudyTimerServiceServer) TimerStatistics(context.Context, *TimerStatisticsRequest) (*TimerStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TimerStatistics not implemented")
}
func (UnimplementedStudyTimerServiceServer) mustEmbedUnimplementedStudyTimerServiceServer() {}
func (UnimplementedStudyTimerServiceServer) testEmbeddedByValue()                           {}

// UnsafeStudyTimerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudyTimerServiceServer will
// result in compilation errors.
type UnsafeStudyTimerServiceServer interface {
	mustEmbedUnimplementedStudyTimerServiceServer()
}

func RegisterStudyTimerServiceServer(s grpc.ServiceRegistrar, srv StudyTimerServiceServer) {
	// If the following call panics, it indicates UnimplementedStudyTimerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudyTimerService_ServiceDesc, srv)
}

func _StudyTimerService_StartTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).StartTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_StartTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).StartTimer(ctx, req.(*StartTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_GetTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).GetTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_GetTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).GetTimer(ctx, req.(*GetTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_GetRoomTimers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomTimersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).GetRoomTimers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_GetRoomTimers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).GetRoomTimers(ctx, req.(*GetRoomTimersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_PauseTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).PauseTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_PauseTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).PauseTimer(ctx, req.(*PauseTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_ResumeTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).ResumeTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_ResumeTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).ResumeTimer(ctx, req.(*ResumeTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_StopTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).StopTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_StopTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).StopTimer(ctx, req.(*StopTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_ResetTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).ResetTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_ResetTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).ResetTimer(ctx, req.(*ResetTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_CompleteCycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteCycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).CompleteCycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_CompleteCycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).CompleteCycle(ctx, req.(*CompleteCycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_SkipRest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkipRestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).SkipRest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_SkipRest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).SkipRest(ctx, req.(*SkipRestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_UpdateTimerSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTimerSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).UpdateTimerSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_UpdateTimerSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).UpdateTimerSetting(ctx, req.(*UpdateTimerSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyTimerService_TimerStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimerStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyTimerServiceServer).TimerStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyTimerService_TimerStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyTimerServiceServer).TimerStatistics(ctx, req.(*TimerStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudyTimerService_ServiceDesc is the grpc.ServiceDesc for StudyTimerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudyTimerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fishertimer.studytimer.v1.StudyTimerService",
	HandlerType: (*StudyTimerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTimer",
			Handler:    _StudyTimerService_StartTimer_Handler,
		},
		{
			MethodName: "GetTimer",
			Handler:    _StudyTimerService_GetTimer_Handler,
		},
		{
			MethodName: "GetRoomTimers",
			Handler:    _StudyTimerService_GetRoomTimers_Handler,
		},
		{
			MethodName: "PauseTimer",
			Handler:    _StudyTimerService_PauseTimer_Handler,
		},
		{
			MethodName: "ResumeTimer",
			Handler:    _StudyTimerService_ResumeTimer_Handler,
		},
		{
			MethodName: "StopTimer",
			Handler:    _StudyTimerService_StopTimer_Handler,
		},
		{
			MethodName: "ResetTimer",
			Handler:    _StudyTimerService_ResetTimer_Handler,
		},
		{
			MethodName: "CompleteCycle",
			Handler:    _StudyTimerService_CompleteCycle_Handler,
		},
		{
			MethodName: "SkipRest",
			Handler:    _StudyTimerService_SkipRest_Handler,
		},
		{
			MethodName: "UpdateTimerSetting",
			Handler:    _StudyTimerService_UpdateTimerSetting_Handler,
		},
		{
			MethodName: "TimerStatistics",
			Handler:    _StudyTimerService_TimerStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studytimer/v1/timer.proto",
}
