// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: studytimer/v1/timer.proto

package timerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimerStatus int32

const (
	TimerStatus_TIMER_STATUS_UNSPECIFIED TimerStatus = 0
	TimerStatus_TIMER_STATUS_STOPPED     TimerStatus = 1
	TimerStatus_TIMER_STATUS_RUNNING     TimerStatus = 2
	TimerStatus_TIMER_STATUS_PAUSED      TimerStatus = 3
)

// Enum value maps for TimerStatus.
var (
	TimerStatus_name = map[int32]string{
		0: "TIMER_STATUS_UNSPECIFIED",
		1: "TIMER_STATUS_STOPPED",
		2: "TIMER_STATUS_RUNNING",
		3: "TIMER_STATUS_PAUSED",
	}
	TimerStatus_value = map[string]int32{
		"TIMER_STATUS_UNSPECIFIED": 0,
		"TIMER_STATUS_STOPPED":     1,
		"TIMER_STATUS_RUNNING":     2,
		"TIMER_STATUS_PAUSED":      3,
	}
)

func (x TimerStatus) Enum() *TimerStatus {
	p := new(TimerStatus)
	*p = x
	return p
}

func (x TimerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_studytimer_v1_timer_proto_enumTypes[0].Descriptor()
}

func (TimerStatus) Type() protoreflect.EnumType {
	return &file_studytimer_v1_timer_proto_enumTypes[0]
}

func (x TimerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimerStatus.Descriptor instead.
func (TimerStatus) EnumDescriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{0}
}

type TimerPhase int32

const (
	TimerPhase_TIMER_PHASE_UNSPECIFIED TimerPhase = 0
	TimerPhase_TIMER_PHASE_WORK        TimerPhase = 1
	TimerPhase_TIMER_PHASE_REST        TimerPhase = 2
)

// Enum value maps for TimerPhase.
var (
	TimerPhase_name = map[int32]string{
		0: "TIMER_PHASE_UNSPECIFIED",
		1: "TIMER_PHASE_WORK",
		2: "TIMER_PHASE_REST",
	}
	TimerPhase_value = map[string]int32{
		"TIMER_PHASE_UNSPECIFIED": 0,
		"TIMER_PHASE_WORK":        1,
		"TIMER_PHASE_REST":        2,
	}
)

func (x TimerPhase) Enum() *TimerPhase {
	p := new(TimerPhase)
	*p = x
	return p
}

func (x TimerPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimerPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_studytimer_v1_timer_proto_enumTypes[1].Descriptor()
}

func (TimerPhase) Type() protoreflect.EnumType {
	return &file_studytimer_v1_timer_proto_enumTypes[1]
}

func (x TimerPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimerPhase.Descriptor instead.
func (TimerPhase) EnumDescriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{1}
}

type StartTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTimerRequest) Reset() {
	*x = StartTimerRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTimerRequest) ProtoMessage() {}

func (x *StartTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTimerRequest.ProtoReflect.Descriptor instead.
func (*StartTimerRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{0}
}

func (x *StartTimerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimerRequest) Reset() {
	*x = GetTimerRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerRequest) ProtoMessage() {}

func (x *GetTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerRequest.ProtoReflect.Descriptor instead.
func (*GetTimerRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{1}
}

func (x *GetTimerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PauseTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTimerRequest) Reset() {
	*x = PauseTimerRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTimerRequest) ProtoMessage() {}

func (x *PauseTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTimerRequest.ProtoReflect.Descriptor instead.
func (*PauseTimerRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{2}
}

func (x *PauseTimerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PauseTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResumeTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTimerRequest) Reset() {
	*x = ResumeTimerRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTimerRequest) ProtoMessage() {}

func (x *ResumeTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTimerRequest.ProtoReflect.Descriptor instead.
func (*ResumeTimerRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeTimerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StopTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTimerRequest) Reset() {
	*x = StopTimerRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTimerRequest) ProtoMessage() {}

func (x *StopTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTimerRequest.ProtoReflect.Descriptor instead.
func (*StopTimerRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{4}
}

func (x *StopTimerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResetTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTimerRequest) Reset() {
	*x = ResetTimerRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTimerRequest) ProtoMessage() {}

func (x *ResetTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTimerRequest.ProtoReflect.Descriptor instead.
func (*ResetTimerRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{5}
}

func (x *ResetTimerRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResetTimerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CompleteCycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCycleRequest) Reset() {
	*x = CompleteCycleRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCycleRequest) ProtoMessage() {}

func (x *CompleteCycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCycleRequest.ProtoReflect.Descriptor instead.
func (*CompleteCycleRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteCycleRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteCycleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SkipRestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipRestRequest) Reset() {
	*x = SkipRestRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipRestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipRestRequest) ProtoMessage() {}

func (x *SkipRestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipRestRequest.ProtoReflect.Descriptor instead.
func (*SkipRestRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{7}
}

func (x *SkipRestRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SkipRestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateTimerSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorkMinutes   int32                  `protobuf:"varint,3,opt,name=work_minutes,json=workMinutes,proto3" json:"work_minutes,omitempty"`
	RestMinutes   int32                  `protobuf:"varint,4,opt,name=rest_minutes,json=restMinutes,proto3" json:"rest_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimerSettingRequest) Reset() {
	*x = UpdateTimerSettingRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimerSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimerSettingRequest) ProtoMessage() {}

func (x *UpdateTimerSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimerSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateTimerSettingRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTimerSettingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateTimerSettingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTimerSettingRequest) GetWorkMinutes() int32 {
	if x != nil {
		return x.WorkMinutes
	}
	return 0
}

func (x *UpdateTimerSettingRequest) GetRestMinutes() int32 {
	if x != nil {
		return x.RestMinutes
	}
	return 0
}

type TimerStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerStatisticsRequest) Reset() {
	*x = TimerStatisticsRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerStatisticsRequest) ProtoMessage() {}

func (x *TimerStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerStatisticsRequest.ProtoReflect.Descriptor instead.
func (*TimerStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{9}
}

func (x *TimerStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TimerStateResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SessionId    string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId       string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status       TimerStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=fishertimer.studytimer.v1.TimerStatus" json:"status,omitempty"`
	Phase        TimerPhase             `protobuf:"varint,4,opt,name=phase,proto3,enum=fishertimer.studytimer.v1.TimerPhase" json:"phase,omitempty"`
	WorkMinutes  int32                  `protobuf:"varint,5,opt,name=work_minutes,json=workMinutes,proto3" json:"work_minutes,omitempty"`
	RestMinutes  int32                  `protobuf:"varint,6,opt,name=rest_minutes,json=restMinutes,proto3" json:"rest_minutes,omitempty"`
	CurrentCycle int32                  `protobuf:"varint,7,opt,name=current_cycle,json=currentCycle,proto3" json:"current_cycle,omitempty"`
	// RFC 3339 timestamp of the last state change.
	LastUpdated string `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Length of the current phase, in seconds.
	DurationSeconds int32 `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Time left in the current phase, computed by the server at response time.
	// Clients count down locally from this value and re-sync with GetTimer.
	RemainingSeconds int32 `protobuf:"varint,10,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimerStateResponse) Reset() {
	*x = TimerStateResponse{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerStateResponse) ProtoMessage() {}

func (x *TimerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerStateResponse.ProtoReflect.Descriptor instead.
func (*TimerStateResponse) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{10}
}

func (x *TimerStateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TimerStateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TimerStateResponse) GetStatus() TimerStatus {
	if x != nil {
		return x.Status
	}
	return TimerStatus_TIMER_STATUS_UNSPECIFIED
}

func (x *TimerStateResponse) GetPhase() TimerPhase {
	if x != nil {
		return x.Phase
	}
	return TimerPhase_TIMER_PHASE_UNSPECIFIED
}

func (x *TimerStateResponse) GetWorkMinutes() int32 {
	if x != nil {
		return x.WorkMinutes
	}
	return 0
}

func (x *TimerStateResponse) GetRestMinutes() int32 {
	if x != nil {
		return x.RestMinutes
	}
	return 0
}

func (x *TimerStateResponse) GetCurrentCycle() int32 {
	if x != nil {
		return x.CurrentCycle
	}
	return 0
}

func (x *TimerStateResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *TimerStateResponse) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TimerStateResponse) GetRemainingSeconds() int32 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

type TimerStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalSessions     int32                  `protobuf:"varint,2,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	TotalFocusMinutes int32                  `protobuf:"varint,3,opt,name=total_focus_minutes,json=totalFocusMinutes,proto3" json:"total_focus_minutes,omitempty"`
	LastActive        string                 `protobuf:"bytes,4,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimerStatisticsResponse) Reset() {
	*x = TimerStatisticsResponse{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerStatisticsResponse) ProtoMessage() {}

func (x *TimerStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerStatisticsResponse.ProtoReflect.Descriptor instead.
func (*TimerStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{11}
}

func (x *TimerStatisticsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TimerStatisticsResponse) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *TimerStatisticsResponse) GetTotalFocusMinutes() int32 {
	if x != nil {
		return x.TotalFocusMinutes
	}
	return 0
}

func (x *TimerStatisticsResponse) GetLastActive() string {
	if x != nil {
		return x.LastActive
	}
	return ""
}

type GetRoomTimersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomTimersRequest) Reset() {
	*x = GetRoomTimersRequest{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomTimersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomTimersRequest) ProtoMessage() {}

func (x *GetRoomTimersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomTimersRequest.ProtoReflect.Descriptor instead.
func (*GetRoomTimersRequest) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomTimersRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetRoomTimersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timers        []*TimerStateResponse  `protobuf:"bytes,1,rep,name=timers,proto3" json:"timers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomTimersResponse) Reset() {
	*x = GetRoomTimersResponse{}
	mi := &file_studytimer_v1_timer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomTimersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomTimersResponse) ProtoMessage() {}

func (x *GetRoomTimersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studytimer_v1_timer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomTimersResponse.ProtoReflect.Descriptor instead.
func (*GetRoomTimersResponse) Descriptor() ([]byte, []int) {
	return file_studytimer_v1_timer_proto_rawDescGZIP(), []int{13}
}

func (x *GetRoomTimersResponse) GetTimers() []*TimerStateResponse {
	if x != nil {
		return x.Timers
	}
	return nil
}

var File_studytimer_v1_timer_proto protoreflect.FileDescriptor

const file_studytimer_v1_timer_proto_rawDesc = "" +
	"\n" +
	"\x19studytimer/v1/timer.proto\x12\x19fishertimer.studytimer.v1\"K\n" +
	"\x11StartTimerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x0fGetTimerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x11PauseTimerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"L\n" +
	"\x12ResumeTimerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x10StopTimerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x11ResetTimerRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"N\n" +
	"\x14CompleteCycleRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x0fSkipRestRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x99\x01\n" +
	"\x19UpdateTimerSettingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fwork_minutes\x18\x03 \x01(\x05R\vworkMinutes\x12!\n" +
	"\frest_minutes\x18\x04 \x01(\x05R\vrestMinutes\"1\n" +
	"\x16TimerStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xaf\x03\n" +
	"\x12TimerStateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.fishertimer.studytimer.v1.TimerStatusR\x06status\x12;\n" +
	"\x05phase\x18\x04 \x01(\x0e2%.fishertimer.studytimer.v1.TimerPhaseR\x05phase\x12!\n" +
	"\fwork_minutes\x18\x05 \x01(\x05R\vworkMinutes\x12!\n" +
	"\frest_minutes\x18\x06 \x01(\x05R\vrestMinutes\x12#\n" +
	"\rcurrent_cycle\x18\a \x01(\x05R\fcurrentCycle\x12!\n" +
	"\flast_updated\x18\b \x01(\tR\vlastUpdated\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x05R\x0fdurationSeconds\x12+\n" +
	"\x11remaining_seconds\x18\n" +
	" \x01(\x05R\x10remainingSeconds\"\xaa\x01\n" +
	"\x17TimerStatisticsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0etotal_sessions\x18\x02 \x01(\x05R\rtotalSessions\x12.\n" +
	"\x13total_focus_minutes\x18\x03 \x01(\x05R\x11totalFocusMinutes\x12\x1f\n" +
	"\vlast_active\x18\x04 \x01(\tR\n" +
	"lastActive\"5\n" +
	"\x14GetRoomTimersRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"^\n" +
	"\x15GetRoomTimersResponse\x12E\n" +
	"\x06timers\x18\x01 \x03(\v2-.fishertimer.studytimer.v1.TimerStateResponseR\x06timers*x\n" +
	"\vTimerStatus\x12\x1c\n" +
	"\x18TIMER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TIMER_STATUS_STOPPED\x10\x01\x12\x18\n" +
	"\x14TIMER_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13TIMER_STATUS_PAUSED\x10\x03*U\n" +
	"\n" +
	"TimerPhase\x12\x1b\n" +
	"\x17TIMER_PHASE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TIMER_PHASE_WORK\x10\x01\x12\x14\n" +
	"\x10TIMER_PHASE_REST\x10\x022\xd2\t\n" +
	"\x11StudyTimerService\x12i\n" +
	"\n" +
	"StartTimer\x12,.fishertimer.studytimer.v1.StartTimerRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12e\n" +
	"\bGetTimer\x12*.fishertimer.studytimer.v1.GetTimerRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12r\n" +
	"\rGetRoomTimers\x12/.fishertimer.studytimer.v1.GetRoomTimersRequest\x1a0.fishertimer.studytimer.v1.GetRoomTimersResponse\x12i\n" +
	"\n" +
	"PauseTimer\x12,.fishertimer.studytimer.v1.PauseTimerRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12k\n" +
	"\vResumeTimer\x12-.fishertimer.studytimer.v1.ResumeTimerRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12g\n" +
	"\tStopTimer\x12+.fishertimer.studytimer.v1.StopTimerRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12i\n" +
	"\n" +
	"ResetTimer\x12,.fishertimer.studytimer.v1.ResetTimerRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12o\n" +
	"\rCompleteCycle\x12/.fishertimer.studytimer.v1.CompleteCycleRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12e\n" +
	"\bSkipRest\x12*.fishertimer.studytimer.v1.SkipRestRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12y\n" +
	"\x12UpdateTimerSetting\x124.fishertimer.studytimer.v1.UpdateTimerSettingRequest\x1a-.fishertimer.studytimer.v1.TimerStateResponse\x12x\n" +
	"\x0fTimerStatistics\x121.fishertimer.studytimer.v1.TimerStatisticsRequest\x1a2.fishertimer.studytimer.v1.TimerStatisticsResponseB=Z;github.com/neennera/fishertimer/proto/studytimer/v1;timerv1b\x06proto3"

var (
	file_studytimer_v1_timer_proto_rawDescOnce sync.Once
	file_studytimer_v1_timer_proto_rawDescData []byte
)

func file_studytimer_v1_timer_proto_rawDescGZIP() []byte {
	file_studytimer_v1_timer_proto_rawDescOnce.Do(func() {
		file_studytimer_v1_timer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_studytimer_v1_timer_proto_rawDesc), len(file_studytimer_v1_timer_proto_rawDesc)))
	})
	return file_studytimer_v1_timer_proto_rawDescData
}

var file_studytimer_v1_timer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_studytimer_v1_timer_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_studytimer_v1_timer_proto_goTypes = []any{
	(TimerStatus)(0),                  // 0: fishertimer.studytimer.v1.TimerStatus
	(TimerPhase)(0),                   // 1: fishertimer.studytimer.v1.TimerPhase
	(*StartTimerRequest)(nil),         // 2: fishertimer.studytimer.v1.StartTimerRequest
	(*GetTimerRequest)(nil),           // 3: fishertimer.studytimer.v1.GetTimerRequest
	(*PauseTimerRequest)(nil),         // 4: fishertimer.studytimer.v1.PauseTimerRequest
	(*ResumeTimerRequest)(nil),        // 5: fishertimer.studytimer.v1.ResumeTimerRequest
	(*StopTimerRequest)(nil),          // 6: fishertimer.studytimer.v1.StopTimerRequest
	(*ResetTimerRequest)(nil),         // 7: fishertimer.studytimer.v1.ResetTimerRequest
	(*CompleteCycleRequest)(nil),      // 8: fishertimer.studytimer.v1.CompleteCycleRequest
	(*SkipRestRequest)(nil),           // 9: fishertimer.studytimer.v1.SkipRestRequest
	(*UpdateTimerSettingRequest)(nil), // 10: fishertimer.studytimer.v1.UpdateTimerSettingRequest
	(*TimerStatisticsRequest)(nil),    // 11: fishertimer.studytimer.v1.TimerStatisticsRequest
	(*TimerStateResponse)(nil),        // 12: fishertimer.studytimer.v1.TimerStateResponse
	(*TimerStatisticsResponse)(nil),   // 13: fishertimer.studytimer.v1.TimerStatisticsResponse
	(*GetRoomTimersRequest)(nil),      // 14: fishertimer.studytimer.v1.GetRoomTimersRequest
	(*GetRoomTimersResponse)(nil),     // 15: fishertimer.studytimer.v1.GetRoomTimersResponse
}
var file_studytimer_v1_timer_proto_depIdxs = []int32{
	0,  // 0: fishertimer.studytimer.v1.TimerStateResponse.status:type_name -> fishertimer.studytimer.v1.TimerStatus
	1,  // 1: fishertimer.studytimer.v1.TimerStateResponse.phase:type_name -> fishertimer.studytimer.v1.TimerPhase
	12, // 2: fishertimer.studytimer.v1.GetRoomTimersResponse.timers:type_name -> fishertimer.studytimer.v1.TimerStateResponse
	2,  // 3: fishertimer.studytimer.v1.StudyTimerService.StartTimer:input_type -> fishertimer.studytimer.v1.StartTimerRequest
	3,  // 4: fishertimer.studytimer.v1.StudyTimerService.GetTimer:input_type -> fishertimer.studytimer.v1.GetTimerRequest
	14, // 5: fishertimer.studytimer.v1.StudyTimerService.GetRoomTimers:input_type -> fishertimer.studytimer.v1.GetRoomTimersRequest
	4,  // 6: fishertimer.studytimer.v1.StudyTimerService.PauseTimer:input_type -> fishertimer.studytimer.v1.PauseTimerRequest
	5,  // 7: fishertimer.studytimer.v1.StudyTimerService.ResumeTimer:input_type -> fishertimer.studytimer.v1.ResumeTimerRequest
	6,  // 8: fishertimer.studytimer.v1.StudyTimerService.StopTimer:input_type -> fishertimer.studytimer.v1.StopTimerRequest
	7,  // 9: fishertimer.studytimer.v1.StudyTimerService.ResetTimer:input_type -> fishertimer.studytimer.v1.ResetTimerRequest
	8,  // 10: fishertimer.studytimer.v1.StudyTimerService.CompleteCycle:input_type -> fishertimer.studytimer.v1.CompleteCycleRequest
	9,  // 11: fishertimer.studytimer.v1.StudyTimerService.SkipRest:input_type -> fishertimer.studytimer.v1.SkipRestRequest
	10, // 12: fishertimer.studytimer.v1.StudyTimerService.UpdateTimerSetting:input_type -> fishertimer.studytimer.v1.UpdateTimerSettingRequest
	11, // 13: fishertimer.studytimer.v1.StudyTimerService.TimerStatistics:input_type -> fishertimer.studytimer.v1.TimerStatisticsRequest
	12, // 14: fishertimer.studytimer.v1.StudyTimerService.StartTimer:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	12, // 15: fishertimer.studytimer.v1.StudyTimerService.GetTimer:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	15, // 16: fishertimer.studytimer.v1.StudyTimerService.GetRoomTimers:output_type -> fishertimer.studytimer.v1.GetRoomTimersResponse
	12, // 17: fishertimer.studytimer.v1.StudyTimerService.PauseTimer:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	12, // 18: fishertimer.studytimer.v1.StudyTimerService.ResumeTimer:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	12, // 19: fishertimer.studytimer.v1.StudyTimerService.StopTimer:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	12, // 20: fishertimer.studytimer.v1.StudyTimerService.ResetTimer:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	12, // 21: fishertimer.studytimer.v1.StudyTimerService.CompleteCycle:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	12, // 22: fishertimer.studytimer.v1.StudyTimerService.SkipRest:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	12, // 23: fishertimer.studytimer.v1.StudyTimerService.UpdateTimerSetting:output_type -> fishertimer.studytimer.v1.TimerStateResponse
	13, // 24: fishertimer.studytimer.v1.StudyTimerService.TimerStatistics:output_type -> fishertimer.studytimer.v1.TimerStatisticsResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_studytimer_v1_timer_proto_init() }
func file_studytimer_v1_timer_proto_init() {
	if File_studytimer_v1_timer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_studytimer_v1_timer_proto_rawDesc), len(file_studytimer_v1_timer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studytimer_v1_timer_proto_goTypes,
		DependencyIndexes: file_studytimer_v1_timer_proto_depIdxs,
		EnumInfos:         file_studytimer_v1_timer_proto_enumTypes,
		MessageInfos:      file_studytimer_v1_timer_proto_msgTypes,
	}.Build()
	File_studytimer_v1_timer_proto = out.File
	file_studytimer_v1_timer_proto_goTypes = nil
	file_studytimer_v1_timer_proto_depIdxs = nil
}
