// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: studysession/v1/session.proto

package sessionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StudySessionService_CreateSession_FullMethodName     = "/fishertimer.studysession.v1.StudySessionService/CreateSession"
	StudySessionService_JoinSession_FullMethodName       = "/fishertimer.studysession.v1.StudySessionService/JoinSession"
	StudySessionService_LeaveSession_FullMethodName      = "/fishertimer.studysession.v1.StudySessionService/LeaveSession"
	StudySessionService_EndSession_FullMethodName        = "/fishertimer.studysession.v1.StudySessionService/EndSession"
	StudySessionService_ListActiveSession_FullMethodName = "/fishertimer.studysession.v1.StudySessionService/ListActiveSession"
	StudySessionService_GetParticipants_FullMethodName   = "/fishertimer.studysession.v1.StudySessionService/GetParticipants"
	StudySessionService_GetSession_FullMethodName        = "/fishertimer.studysession.v1.StudySessionService/GetSession"
	StudySessionService_GetMySession_FullMethodName      = "/fishertimer.studysession.v1.StudySessionService/GetMySession"
	StudySessionService_Heartbeat_FullMethodName         = "/fishertimer.studysession.v1.StudySessionService/Heartbeat"
)

// StudySessionServiceClient is the client API for StudySessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StudySessionService owns study rooms and who is in them (UC-01..04).
// Every change to room membership is also published to RabbitMQ
// (exchange fisher.session) so Study Timer can open and finalize timers.
//
// Errors are gRPC status codes, so callers can branch without parsing text:
//
//	INVALID_ARGUMENT     bad name / limit / ids              (UC-01 E-1)
//	NOT_FOUND            no such room
//	FAILED_PRECONDITION  room has ended                      (UC-02 E-1)
//	RESOURCE_EXHAUSTED   room is full                        (UC-02 E-2)
//	ALREADY_EXISTS       user is already in another room     (UC-01 E-2, UC-02 E-3)
type StudySessionServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*StudySessionResponse, error)
	JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*JoinSessionResponse, error)
	// Idempotent: leaving a room you already left is a successful no-op (UC-04 E-4).
	LeaveSession(ctx context.Context, in *LeaveSessionRequest, opts ...grpc.CallOption) (*LeaveSessionResponse, error)
	// Idempotent: ending an ended room is a successful no-op.
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*StudySessionResponse, error)
	ListActiveSession(ctx context.Context, in *ListActiveSessionRequest, opts ...grpc.CallOption) (*ListActiveSessionResponse, error)
	// Active participants only (left_at IS NULL).
	GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*StudySessionResponse, error)
	// The room the user is currently in, if any.
	GetMySession(ctx context.Context, in *GetMySessionRequest, opts ...grpc.CallOption) (*GetMySessionResponse, error)
	// Presence ping from an open room page. A participant whose pings stop is
	// auto-left with reason DISCONNECT_TIMEOUT (UC-03 E-3).
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type studySessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudySessionServiceClient(cc grpc.ClientConnInterface) StudySessionServiceClient {
	return &studySessionServiceClient{cc}
}

func (c *studySessionServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*StudySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudySessionResponse)
	err := c.cc.Invoke(ctx, StudySessionService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*JoinSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinSessionResponse)
	err := c.cc.Invoke(ctx, StudySessionService_JoinSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) LeaveSession(ctx context.Context, in *LeaveSessionRequest, opts ...grpc.CallOption) (*LeaveSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveSessionResponse)
	err := c.cc.Invoke(ctx, StudySessionService_LeaveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*StudySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudySessionResponse)
	err := c.cc.Invoke(ctx, StudySessionService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) ListActiveSession(ctx context.Context, in *ListActiveSessionRequest, opts ...grpc.CallOption) (*ListActiveSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveSessionResponse)
	err := c.cc.Invoke(ctx, StudySessionService_ListActiveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipantsResponse)
	err := c.cc.Invoke(ctx, StudySessionService_GetParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*StudySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudySessionResponse)
	err := c.cc.Invoke(ctx, StudySessionService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) GetMySession(ctx context.Context, in *GetMySessionRequest, opts ...grpc.CallOption) (*GetMySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMySessionResponse)
	err := c.cc.Invoke(ctx, StudySessionService_GetMySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studySessionServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, StudySessionService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudySessionServiceServer is the server API for StudySessionService service.
// All implementations must embed UnimplementedStudySessionServiceServer
// for forward compatibility.
//
// StudySessionService owns study rooms and who is in them (UC-01..04).
// Every change to room membership is also published to RabbitMQ
// (exchange fisher.session) so Study Timer can open and finalize timers.
//
// Errors are gRPC status codes, so callers can branch without parsing text:
//
//	INVALID_ARGUMENT     bad name / limit / ids              (UC-01 E-1)
//	NOT_FOUND            no such room
//	FAILED_PRECONDITION  room has ended                      (UC-02 E-1)
//	RESOURCE_EXHAUSTED   room is full                        (UC-02 E-2)
//	ALREADY_EXISTS       user is already in another room     (UC-01 E-2, UC-02 E-3)
type StudySessionServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*StudySessionResponse, error)
	JoinSession(context.Context, *JoinSessionRequest) (*JoinSessionResponse, error)
	// Idempotent: leaving a room you already left is a successful no-op (UC-04 E-4).
	LeaveSession(context.Context, *LeaveSessionRequest) (*LeaveSessionResponse, error)
	// Idempotent: ending an ended room is a successful no-op.
	EndSession(context.Context, *EndSessionRequest) (*StudySessionResponse, error)
	ListActiveSession(context.Context, *ListActiveSessionRequest) (*ListActiveSessionResponse, error)
	// Active participants only (left_at IS NULL).
	GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*StudySessionResponse, error)
	// The room the user is currently in, if any.
	GetMySession(context.Context, *GetMySessionRequest) (*GetMySessionResponse, error)
	// Presence ping from an open room page. A participant whose pings stop is
	// auto-left with reason DISCONNECT_TIMEOUT (UC-03 E-3).
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedStudySessionServiceServer()
}

// UnimplementedStudySessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudySessionServiceServer struct{}

func (UnimplementedStudySessionServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*StudySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedStudySessionServiceServer) JoinSession(context.Context, *JoinSessionRequest) (*JoinSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinSession not implemented")
}
func (UnimplementedStudySessionServiceServer) LeaveSession(context.Context, *LeaveSessionRequest) (*LeaveSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveSession not implemented")
}
func (UnimplementedStudySessionServiceServer) EndSession(context.Context, *EndSessionRequest) (*StudySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedStudySessionServiceServer) ListActiveSession(context.Context, *ListActiveSessionRequest) (*ListActiveSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveSession not implemented")
}
func (UnimplementedStudySessionServiceServer) GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParticipants not implemented")
}
func (UnimplementedStudySessionServiceServer) GetSession(context.Context, *GetSessionRequest) (*StudySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedStudySessionServiceServer) GetMySession(context.Context, *GetMySessionRequest) (*GetMySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMySession not implemented")
}
func (UnimplementedStudySessionServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedStudySessionServiceServer) mustEmbedUnimplementedStudySessionServiceServer() {}
func (UnimplementedStudySessionServiceServer) testEmbeddedByValue()                             {}

// UnsafeStudySessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudySessionServiceServer will
// result in compilation errors.
type UnsafeStudySessionServiceServer interface {
	mustEmbedUnimplementedStudySessionServiceServer()
}

func RegisterStudySessionServiceServer(s grpc.ServiceRegistrar, srv StudySessionServiceServer) {
	// If the following call panics, it indicates UnimplementedStudySessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudySessionService_ServiceDesc, srv)
}

func _StudySessionService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_JoinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).JoinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_JoinSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).JoinSession(ctx, req.(*JoinSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_LeaveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).LeaveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_LeaveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).LeaveSession(ctx, req.(*LeaveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_ListActiveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).ListActiveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_ListActiveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).ListActiveSession(ctx, req.(*ListActiveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_GetParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).GetParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_GetParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).GetParticipants(ctx, req.(*GetParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_GetMySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).GetMySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_GetMySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).GetMySession(ctx, req.(*GetMySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudySessionService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudySessionServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudySessionService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudySessionServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudySessionService_ServiceDesc is the grpc.ServiceDesc for StudySessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudySessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fishertimer.studysession.v1.StudySessionService",
	HandlerType: (*StudySessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _StudySessionService_CreateSession_Handler,
		},
		{
			MethodName: "JoinSession",
			Handler:    _StudySessionService_JoinSession_Handler,
		},
		{
			MethodName: "LeaveSession",
			Handler:    _StudySessionService_LeaveSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _StudySessionService_EndSession_Handler,
		},
		{
			MethodName: "ListActiveSession",
			Handler:    _StudySessionService_ListActiveSession_Handler,
		},
		{
			MethodName: "GetParticipants",
			Handler:    _StudySessionService_GetParticipants_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _StudySessionService_GetSession_Handler,
		},
		{
			MethodName: "GetMySession",
			Handler:    _StudySessionService_GetMySession_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _StudySessionService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studysession/v1/session.proto",
}
