// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: studysession/v1/session.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId          string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParticipantLimit   int32                  `protobuf:"varint,3,opt,name=participant_limit,json=participantLimit,proto3" json:"participant_limit,omitempty"`
	CreatorDisplayName string                 `protobuf:"bytes,4,opt,name=creator_display_name,json=creatorDisplayName,proto3" json:"creator_display_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateSessionRequest) GetParticipantLimit() int32 {
	if x != nil {
		return x.ParticipantLimit
	}
	return 0
}

func (x *CreateSessionRequest) GetCreatorDisplayName() string {
	if x != nil {
		return x.CreatorDisplayName
	}
	return ""
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinSessionRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type JoinSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Session       *StudySessionResponse  `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionResponse) Reset() {
	*x = JoinSessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionResponse) ProtoMessage() {}

func (x *JoinSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinSessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *JoinSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinSessionResponse) GetSession() *StudySessionResponse {
	if x != nil {
		return x.Session
	}
	return nil
}

type LeaveSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// LEFT (default) | KICKED | DISCONNECT_TIMEOUT | IDLE_TIMEOUT
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionRequest) Reset() {
	*x = LeaveSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionRequest) ProtoMessage() {}

func (x *LeaveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionRequest.ProtoReflect.Descriptor instead.
func (*LeaveSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LeaveSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LeaveSessionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// False when the user had already left (no-op).
	Left bool `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	// True when this leave emptied the room and ended it (UC-03 S-2).
	SessionEnded  bool   `protobuf:"varint,3,opt,name=session_ended,json=sessionEnded,proto3" json:"session_ended,omitempty"`
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinedAt      string `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt        string `protobuf:"bytes,7,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionResponse) Reset() {
	*x = LeaveSessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionResponse) ProtoMessage() {}

func (x *LeaveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionResponse.ProtoReflect.Descriptor instead.
func (*LeaveSessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveSessionResponse) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *LeaveSessionResponse) GetSessionEnded() bool {
	if x != nil {
		return x.SessionEnded
	}
	return false
}

func (x *LeaveSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LeaveSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveSessionResponse) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *LeaveSessionResponse) GetLeftAt() string {
	if x != nil {
		return x.LeftAt
	}
	return ""
}

type EndSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Kept for compatibility; who asked is not needed to end a room.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// ADMIN_CLOSED (default) | EMPTY | TIMEOUT_24H
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EndSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ListActiveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionRequest) Reset() {
	*x = ListActiveSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionRequest) ProtoMessage() {}

func (x *ListActiveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionRequest.ProtoReflect.Descriptor instead.
func (*ListActiveSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{6}
}

type ParticipantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantInfo) Reset() {
	*x = ParticipantInfo{}
	mi := &file_studysession_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInfo) ProtoMessage() {}

func (x *ParticipantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInfo.ProtoReflect.Descriptor instead.
func (*ParticipantInfo) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *ParticipantInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ParticipantInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParticipantInfo) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *ParticipantInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ParticipantInfo) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

type StudySessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId        string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParticipantLimit int32                  `protobuf:"varint,4,opt,name=participant_limit,json=participantLimit,proto3" json:"participant_limit,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ParticipantCount int32                  `protobuf:"varint,7,opt,name=participant_count,json=participantCount,proto3" json:"participant_count,omitempty"`
	EndedAt          string                 `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	EndReason        string                 `protobuf:"bytes,9,opt,name=end_reason,json=endReason,proto3" json:"end_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StudySessionResponse) Reset() {
	*x = StudySessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudySessionResponse) ProtoMessage() {}

func (x *StudySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudySessionResponse.ProtoReflect.Descriptor instead.
func (*StudySessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *StudySessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudySessionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudySessionResponse) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *StudySessionResponse) GetParticipantLimit() int32 {
	if x != nil {
		return x.ParticipantLimit
	}
	return 0
}

func (x *StudySessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StudySessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StudySessionResponse) GetParticipantCount() int32 {
	if x != nil {
		return x.ParticipantCount
	}
	return 0
}

func (x *StudySessionResponse) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *StudySessionResponse) GetEndReason() string {
	if x != nil {
		return x.EndReason
	}
	return ""
}

type ListActiveSessionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sessions      []*StudySessionResponse `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionResponse) Reset() {
	*x = ListActiveSessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionResponse) ProtoMessage() {}

func (x *ListActiveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionResponse.ProtoReflect.Descriptor instead.
func (*ListActiveSessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ListActiveSessionResponse) GetSessions() []*StudySessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsRequest) Reset() {
	*x = GetParticipantsRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsRequest) ProtoMessage() {}

func (x *GetParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *GetParticipantsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*ParticipantInfo     `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsResponse) Reset() {
	*x = GetParticipantsResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsResponse) ProtoMessage() {}

func (x *GetParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *GetParticipantsResponse) GetParticipants() []*ParticipantInfo {
	if x != nil {
		return x.Participants
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetMySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySessionRequest) Reset() {
	*x = GetMySessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySessionRequest) ProtoMessage() {}

func (x *GetMySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySessionRequest.ProtoReflect.Descriptor instead.
func (*GetMySessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *GetMySessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InSession     bool                   `protobuf:"varint,1,opt,name=in_session,json=inSession,proto3" json:"in_session,omitempty"`
	Session       *StudySessionResponse  `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Participant   *ParticipantInfo       `protobuf:"bytes,3,opt,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySessionResponse) Reset() {
	*x = GetMySessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySessionResponse) ProtoMessage() {}

func (x *GetMySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySessionResponse.ProtoReflect.Descriptor instead.
func (*GetMySessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *GetMySessionResponse) GetInSession() bool {
	if x != nil {
		return x.InSession
	}
	return false
}

func (x *GetMySessionResponse) GetSession() *StudySessionResponse {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetMySessionResponse) GetParticipant() *ParticipantInfo {
	if x != nil {
		return x.Participant
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False once the user is no longer in the room (left, kicked, timed out,
	// or the room ended); the page should then leave.
	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	// Why the user is no longer active, when known: a leave reason
	// (KICKED, IDLE_TIMEOUT, ...) or SESSION_ENDED.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HeartbeatResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_studysession_v1_session_proto protoreflect.FileDescriptor

const file_studysession_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1dstudysession/v1/session.proto\x12\x1bfishertimer.studysession.v1\"\xa8\x01\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12+\n" +
	"\x11participant_limit\x18\x03 \x01(\x05R\x10participantLimit\x120\n" +
	"\x14creator_display_name\x18\x04 \x01(\tR\x12creatorDisplayName\"o\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"|\n" +
	"\x13JoinSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12K\n" +
	"\asession\x18\x02 \x01(\v21.fishertimer.studysession.v1.StudySessionResponseR\asession\"e\n" +
	"\x13LeaveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xd7\x01\n" +
	"\x14LeaveSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04left\x18\x02 \x01(\bR\x04left\x12#\n" +
	"\rsession_ended\x18\x03 \x01(\bR\fsessionEnded\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\tR\bjoinedAt\x12\x17\n" +
	"\aleft_at\x18\a \x01(\tR\x06leftAt\"c\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x1a\n" +
	"\x18ListActiveSessionRequest\"\xab\x01\n" +
	"\x0fParticipantInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\tR\bjoinedAt\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12 \n" +
	"\flast_seen_at\x18\x05 \x01(\tR\n" +
	"lastSeenAt\"\xa4\x02\n" +
	"\x14StudySessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\x12+\n" +
	"\x11participant_limit\x18\x04 \x01(\x05R\x10participantLimit\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12+\n" +
	"\x11participant_count\x18\a \x01(\x05R\x10participantCount\x12\x19\n" +
	"\bended_at\x18\b \x01(\tR\aendedAt\x12\x1d\n" +
	"\n" +
	"end_reason\x18\t \x01(\tR\tendReason\"j\n" +
	"\x19ListActiveSessionResponse\x12M\n" +
	"\bsessions\x18\x01 \x03(\v21.fishertimer.studysession.v1.StudySessionResponseR\bsessions\"7\n" +
	"\x16GetParticipantsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"k\n" +
	"\x17GetParticipantsResponse\x12P\n" +
	"\fparticipants\x18\x01 \x03(\v2,.fishertimer.studysession.v1.ParticipantInfoR\fparticipants\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\x13GetMySessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd2\x01\n" +
	"\x14GetMySessionResponse\x12\x1d\n" +
	"\n" +
	"in_session\x18\x01 \x01(\bR\tinSession\x12K\n" +
	"\asession\x18\x02 \x01(\v21.fishertimer.studysession.v1.StudySessionResponseR\asession\x12N\n" +
	"\vparticipant\x18\x03 \x01(\v2,.fishertimer.studysession.v1.ParticipantInfoR\vparticipant\"J\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"C\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xb9\b\n" +
	"\x13StudySessionService\x12u\n" +
	"\rCreateSession\x121.fishertimer.studysession.v1.CreateSessionRequest\x1a1.fishertimer.studysession.v1.StudySessionResponse\x12p\n" +
	"\vJoinSession\x12/.fishertimer.studysession.v1.JoinSessionRequest\x1a0.fishertimer.studysession.v1.JoinSessionResponse\x12s\n" +
	"\fLeaveSession\x120.fishertimer.studysession.v1.LeaveSessionRequest\x1a1.fishertimer.studysession.v1.LeaveSessionResponse\x12o\n" +
	"\n" +
	"EndSession\x12..fishertimer.studysession.v1.EndSessionRequest\x1a1.fishertimer.studysession.v1.StudySessionResponse\x12\x82\x01\n" +
	"\x11ListActiveSession\x125.fishertimer.studysession.v1.ListActiveSessionRequest\x1a6.fishertimer.studysession.v1.ListActiveSessionResponse\x12|\n" +
	"\x0fGetParticipants\x123.fishertimer.studysession.v1.GetParticipantsRequest\x1a4.fishertimer.studysession.v1.GetParticipantsResponse\x12o\n" +
	"\n" +
	"GetSession\x12..fishertimer.studysession.v1.GetSessionRequest\x1a1.fishertimer.studysession.v1.StudySessionResponse\x12s\n" +
	"\fGetMySession\x120.fishertimer.studysession.v1.GetMySessionRequest\x1a1.fishertimer.studysession.v1.GetMySessionResponse\x12j\n" +
	"\tHeartbeat\x12-.fishertimer.studysession.v1.HeartbeatRequest\x1a..fishertimer.studysession.v1.HeartbeatResponseBAZ?github.com/neennera/fishertimer/proto/studysession/v1;sessionv1b\x06proto3"

var (
	file_studysession_v1_session_proto_rawDescOnce sync.Once
	file_studysession_v1_session_proto_rawDescData []byte
)

func file_studysession_v1_session_proto_rawDescGZIP() []byte {
	file_studysession_v1_session_proto_rawDescOnce.Do(func() {
		file_studysession_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_studysession_v1_session_proto_rawDesc), len(file_studysession_v1_session_proto_rawDesc)))
	})
	return file_studysession_v1_session_proto_rawDescData
}

var file_studysession_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_studysession_v1_session_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),      // 0: fishertimer.studysession.v1.CreateSessionRequest
	(*JoinSessionRequest)(nil),        // 1: fishertimer.studysession.v1.JoinSessionRequest
	(*JoinSessionResponse)(nil),       // 2: fishertimer.studysession.v1.JoinSessionResponse
	(*LeaveSessionRequest)(nil),       // 3: fishertimer.studysession.v1.LeaveSessionRequest
	(*LeaveSessionResponse)(nil),      // 4: fishertimer.studysession.v1.LeaveSessionResponse
	(*EndSessionRequest)(nil),         // 5: fishertimer.studysession.v1.EndSessionRequest
	(*ListActiveSessionRequest)(nil),  // 6: fishertimer.studysession.v1.ListActiveSessionRequest
	(*ParticipantInfo)(nil),           // 7: fishertimer.studysession.v1.ParticipantInfo
	(*StudySessionResponse)(nil),      // 8: fishertimer.studysession.v1.StudySessionResponse
	(*ListActiveSessionResponse)(nil), // 9: fishertimer.studysession.v1.ListActiveSessionResponse
	(*GetParticipantsRequest)(nil),    // 10: fishertimer.studysession.v1.GetParticipantsRequest
	(*GetParticipantsResponse)(nil),   // 11: fishertimer.studysession.v1.GetParticipantsResponse
	(*GetSessionRequest)(nil),         // 12: fishertimer.studysession.v1.GetSessionRequest
	(*GetMySessionRequest)(nil),       // 13: fishertimer.studysession.v1.GetMySessionRequest
	(*GetMySessionResponse)(nil),      // 14: fishertimer.studysession.v1.GetMySessionResponse
	(*HeartbeatRequest)(nil),          // 15: fishertimer.studysession.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 16: fishertimer.studysession.v1.HeartbeatResponse
}
var file_studysession_v1_session_proto_depIdxs = []int32{
	8,  // 0: fishertimer.studysession.v1.JoinSessionResponse.session:type_name -> fishertimer.studysession.v1.StudySessionResponse
	8,  // 1: fishertimer.studysession.v1.ListActiveSessionResponse.sessions:type_name -> fishertimer.studysession.v1.StudySessionResponse
	7,  // 2: fishertimer.studysession.v1.GetParticipantsResponse.participants:type_name -> fishertimer.studysession.v1.ParticipantInfo
	8,  // 3: fishertimer.studysession.v1.GetMySessionResponse.session:type_name -> fishertimer.studysession.v1.StudySessionResponse
	7,  // 4: fishertimer.studysession.v1.GetMySessionResponse.participant:type_name -> fishertimer.studysession.v1.ParticipantInfo
	0,  // 5: fishertimer.studysession.v1.StudySessionService.CreateSession:input_type -> fishertimer.studysession.v1.CreateSessionRequest
	1,  // 6: fishertimer.studysession.v1.StudySessionService.JoinSession:input_type -> fishertimer.studysession.v1.JoinSessionRequest
	3,  // 7: fishertimer.studysession.v1.StudySessionService.LeaveSession:input_type -> fishertimer.studysession.v1.LeaveSessionRequest
	5,  // 8: fishertimer.studysession.v1.StudySessionService.EndSession:input_type -> fishertimer.studysession.v1.EndSessionRequest
	6,  // 9: fishertimer.studysession.v1.StudySessionService.ListActiveSession:input_type -> fishertimer.studysession.v1.ListActiveSessionRequest
	10, // 10: fishertimer.studysession.v1.StudySessionService.GetParticipants:input_type -> fishertimer.studysession.v1.GetParticipantsRequest
	12, // 11: fishertimer.studysession.v1.StudySessionService.GetSession:input_type -> fishertimer.studysession.v1.GetSessionRequest
	13, // 12: fishertimer.studysession.v1.StudySessionService.GetMySession:input_type -> fishertimer.studysession.v1.GetMySessionRequest
	15, // 13: fishertimer.studysession.v1.StudySessionService.Heartbeat:input_type -> fishertimer.studysession.v1.HeartbeatRequest
	8,  // 14: fishertimer.studysession.v1.StudySessionService.CreateSession:output_type -> fishertimer.studysession.v1.StudySessionResponse
	2,  // 15: fishertimer.studysession.v1.StudySessionService.JoinSession:output_type -> fishertimer.studysession.v1.JoinSessionResponse
	4,  // 16: fishertimer.studysession.v1.StudySessionService.LeaveSession:output_type -> fishertimer.studysession.v1.LeaveSessionResponse
	8,  // 17: fishertimer.studysession.v1.StudySessionService.EndSession:output_type -> fishertimer.studysession.v1.StudySessionResponse
	9,  // 18: fishertimer.studysession.v1.StudySessionService.ListActiveSession:output_type -> fishertimer.studysession.v1.ListActiveSessionResponse
	11, // 19: fishertimer.studysession.v1.StudySessionService.GetParticipants:output_type -> fishertimer.studysession.v1.GetParticipantsResponse
	8,  // 20: fishertimer.studysession.v1.StudySessionService.GetSession:output_type -> fishertimer.studysession.v1.StudySessionResponse
	14, // 21: fishertimer.studysession.v1.StudySessionService.GetMySession:output_type -> fishertimer.studysession.v1.GetMySessionResponse
	16, // 22: fishertimer.studysession.v1.StudySessionService.Heartbeat:output_type -> fishertimer.studysession.v1.HeartbeatResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_studysession_v1_session_proto_init() }
func file_studysession_v1_session_proto_init() {
	if File_studysession_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_studysession_v1_session_proto_rawDesc), len(file_studysession_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studysession_v1_session_proto_goTypes,
		DependencyIndexes: file_studysession_v1_session_proto_depIdxs,
		MessageInfos:      file_studysession_v1_session_proto_msgTypes,
	}.Build()
	File_studysession_v1_session_proto = out.File
	file_studysession_v1_session_proto_goTypes = nil
	file_studysession_v1_session_proto_depIdxs = nil
}
