// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: studysession/v1/session.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId        string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParticipantLimit int32                  `protobuf:"varint,3,opt,name=participant_limit,json=participantLimit,proto3" json:"participant_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateSessionRequest) GetParticipantLimit() int32 {
	if x != nil {
		return x.ParticipantLimit
	}
	return 0
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionResponse) Reset() {
	*x = JoinSessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionResponse) ProtoMessage() {}

func (x *JoinSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinSessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *JoinSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionRequest) Reset() {
	*x = LeaveSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionRequest) ProtoMessage() {}

func (x *LeaveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionRequest.ProtoReflect.Descriptor instead.
func (*LeaveSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LeaveSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionResponse) Reset() {
	*x = LeaveSessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionResponse) ProtoMessage() {}

func (x *LeaveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionResponse.ProtoReflect.Descriptor instead.
func (*LeaveSessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListActiveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionRequest) Reset() {
	*x = ListActiveSessionRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionRequest) ProtoMessage() {}

func (x *ListActiveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionRequest.ProtoReflect.Descriptor instead.
func (*ListActiveSessionRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{6}
}

type ParticipantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantInfo) Reset() {
	*x = ParticipantInfo{}
	mi := &file_studysession_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInfo) ProtoMessage() {}

func (x *ParticipantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInfo.ProtoReflect.Descriptor instead.
func (*ParticipantInfo) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *ParticipantInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ParticipantInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParticipantInfo) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

type StudySessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId        string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParticipantLimit int32                  `protobuf:"varint,4,opt,name=participant_limit,json=participantLimit,proto3" json:"participant_limit,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StudySessionResponse) Reset() {
	*x = StudySessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudySessionResponse) ProtoMessage() {}

func (x *StudySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudySessionResponse.ProtoReflect.Descriptor instead.
func (*StudySessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *StudySessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudySessionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudySessionResponse) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *StudySessionResponse) GetParticipantLimit() int32 {
	if x != nil {
		return x.ParticipantLimit
	}
	return 0
}

func (x *StudySessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StudySessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListActiveSessionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sessions      []*StudySessionResponse `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionResponse) Reset() {
	*x = ListActiveSessionResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionResponse) ProtoMessage() {}

func (x *ListActiveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionResponse.ProtoReflect.Descriptor instead.
func (*ListActiveSessionResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ListActiveSessionResponse) GetSessions() []*StudySessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsRequest) Reset() {
	*x = GetParticipantsRequest{}
	mi := &file_studysession_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsRequest) ProtoMessage() {}

func (x *GetParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *GetParticipantsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*ParticipantInfo     `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsResponse) Reset() {
	*x = GetParticipantsResponse{}
	mi := &file_studysession_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsResponse) ProtoMessage() {}

func (x *GetParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studysession_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_studysession_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *GetParticipantsResponse) GetParticipants() []*ParticipantInfo {
	if x != nil {
		return x.Participants
	}
	return nil
}

var File_studysession_v1_session_proto protoreflect.FileDescriptor

const file_studysession_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1dstudysession/v1/session.proto\x12\x1bfishertimer.studysession.v1\"v\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12+\n" +
	"\x11participant_limit\x18\x03 \x01(\x05R\x10participantLimit\"L\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13JoinSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x13LeaveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x14LeaveSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1a\n" +
	"\x18ListActiveSessionRequest\"f\n" +
	"\x0fParticipantInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\tR\bjoinedAt\"\xbd\x01\n" +
	"\x14StudySessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\x12+\n" +
	"\x11participant_limit\x18\x04 \x01(\x05R\x10participantLimit\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"j\n" +
	"\x19ListActiveSessionResponse\x12M\n" +
	"\bsessions\x18\x01 \x03(\v21.fishertimer.studysession.v1.StudySessionResponseR\bsessions\"7\n" +
	"\x16GetParticipantsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"k\n" +
	"\x17GetParticipantsResponse\x12P\n" +
	"\fparticipants\x18\x01 \x03(\v2,.fishertimer.studysession.v1.ParticipantInfoR\fparticipants2\xe7\x05\n" +
	"\x13StudySessionService\x12u\n" +
	"\rCreateSession\x121.fishertimer.studysession.v1.CreateSessionRequest\x1a1.fishertimer.studysession.v1.StudySessionResponse\x12p\n" +
	"\vJoinSession\x12/.fishertimer.studysession.v1.JoinSessionRequest\x1a0.fishertimer.studysession.v1.JoinSessionResponse\x12s\n" +
	"\fLeaveSession\x120.fishertimer.studysession.v1.LeaveSessionRequest\x1a1.fishertimer.studysession.v1.LeaveSessionResponse\x12o\n" +
	"\n" +
	"EndSession\x12..fishertimer.studysession.v1.EndSessionRequest\x1a1.fishertimer.studysession.v1.StudySessionResponse\x12\x82\x01\n" +
	"\x11ListActiveSession\x125.fishertimer.studysession.v1.ListActiveSessionRequest\x1a6.fishertimer.studysession.v1.ListActiveSessionResponse\x12|\n" +
	"\x0fGetParticipants\x123.fishertimer.studysession.v1.GetParticipantsRequest\x1a4.fishertimer.studysession.v1.GetParticipantsResponseBAZ?github.com/neennera/fishertimer/proto/studysession/v1;sessionv1b\x06proto3"

var (
	file_studysession_v1_session_proto_rawDescOnce sync.Once
	file_studysession_v1_session_proto_rawDescData []byte
)

func file_studysession_v1_session_proto_rawDescGZIP() []byte {
	file_studysession_v1_session_proto_rawDescOnce.Do(func() {
		file_studysession_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_studysession_v1_session_proto_rawDesc), len(file_studysession_v1_session_proto_rawDesc)))
	})
	return file_studysession_v1_session_proto_rawDescData
}

var file_studysession_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_studysession_v1_session_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),      // 0: fishertimer.studysession.v1.CreateSessionRequest
	(*JoinSessionRequest)(nil),        // 1: fishertimer.studysession.v1.JoinSessionRequest
	(*JoinSessionResponse)(nil),       // 2: fishertimer.studysession.v1.JoinSessionResponse
	(*LeaveSessionRequest)(nil),       // 3: fishertimer.studysession.v1.LeaveSessionRequest
	(*LeaveSessionResponse)(nil),      // 4: fishertimer.studysession.v1.LeaveSessionResponse
	(*EndSessionRequest)(nil),         // 5: fishertimer.studysession.v1.EndSessionRequest
	(*ListActiveSessionRequest)(nil),  // 6: fishertimer.studysession.v1.ListActiveSessionRequest
	(*ParticipantInfo)(nil),           // 7: fishertimer.studysession.v1.ParticipantInfo
	(*StudySessionResponse)(nil),      // 8: fishertimer.studysession.v1.StudySessionResponse
	(*ListActiveSessionResponse)(nil), // 9: fishertimer.studysession.v1.ListActiveSessionResponse
	(*GetParticipantsRequest)(nil),    // 10: fishertimer.studysession.v1.GetParticipantsRequest
	(*GetParticipantsResponse)(nil),   // 11: fishertimer.studysession.v1.GetParticipantsResponse
}
var file_studysession_v1_session_proto_depIdxs = []int32{
	8,  // 0: fishertimer.studysession.v1.ListActiveSessionResponse.sessions:type_name -> fishertimer.studysession.v1.StudySessionResponse
	7,  // 1: fishertimer.studysession.v1.GetParticipantsResponse.participants:type_name -> fishertimer.studysession.v1.ParticipantInfo
	0,  // 2: fishertimer.studysession.v1.StudySessionService.CreateSession:input_type -> fishertimer.studysession.v1.CreateSessionRequest
	1,  // 3: fishertimer.studysession.v1.StudySessionService.JoinSession:input_type -> fishertimer.studysession.v1.JoinSessionRequest
	3,  // 4: fishertimer.studysession.v1.StudySessionService.LeaveSession:input_type -> fishertimer.studysession.v1.LeaveSessionRequest
	5,  // 5: fishertimer.studysession.v1.StudySessionService.EndSession:input_type -> fishertimer.studysession.v1.EndSessionRequest
	6,  // 6: fishertimer.studysession.v1.StudySessionService.ListActiveSession:input_type -> fishertimer.studysession.v1.ListActiveSessionRequest
	10, // 7: fishertimer.studysession.v1.StudySessionService.GetParticipants:input_type -> fishertimer.studysession.v1.GetParticipantsRequest
	8,  // 8: fishertimer.studysession.v1.StudySessionService.CreateSession:output_type -> fishertimer.studysession.v1.StudySessionResponse
	2,  // 9: fishertimer.studysession.v1.StudySessionService.JoinSession:output_type -> fishertimer.studysession.v1.JoinSessionResponse
	4,  // 10: fishertimer.studysession.v1.StudySessionService.LeaveSession:output_type -> fishertimer.studysession.v1.LeaveSessionResponse
	8,  // 11: fishertimer.studysession.v1.StudySessionService.EndSession:output_type -> fishertimer.studysession.v1.StudySessionResponse
	9,  // 12: fishertimer.studysession.v1.StudySessionService.ListActiveSession:output_type -> fishertimer.studysession.v1.ListActiveSessionResponse
	11, // 13: fishertimer.studysession.v1.StudySessionService.GetParticipants:output_type -> fishertimer.studysession.v1.GetParticipantsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_studysession_v1_session_proto_init() }
func file_studysession_v1_session_proto_init() {
	if File_studysession_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_studysession_v1_session_proto_rawDesc), len(file_studysession_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studysession_v1_session_proto_goTypes,
		DependencyIndexes: file_studysession_v1_session_proto_depIdxs,
		MessageInfos:      file_studysession_v1_session_proto_msgTypes,
	}.Build()
	File_studysession_v1_session_proto = out.File
	file_studysession_v1_session_proto_goTypes = nil
	file_studysession_v1_session_proto_depIdxs = nil
}
